.PHONY: all server client

help:
	@echo "Targets:"
	@echo "  make all"
	@echo "  make server"
	@echo "  make client"

all: server client

server:
	g++ server.cpp -o server

client:
	g++ client.cpp -o client
